=== Parameter-Name Object
==== Overview
The `parameter-name` object provides information about a data parameter supported by a Collection. The Collection may expose several `parameter-name` objects, as a set of key-value pairs, where the key is the name of the parameter and the value is a <<col-parameter, Parameter>> object i.e. as a Dictionary (Python) or HashMap(Java).

==== Source Reference
It is defined in the https://docs.ogc.org/is/19-086r5/19-086r5.htm[OGC API-EDR V1.0.1 specification, Section 8.2.1.3] which is maintained by the OGC EDR API Standard Working Group using this https://github.com/opengeospatial/ogcapi-environmental-data-retrieval[OGC GitHub repository].

==== Maturity
Mature

[[col-parameter]]
==== Pre-defined Properties of the Parameter-Name Object 
[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Parameter Object
|==========================
|Field Name|Type|Required|Description
|id  |String|No| parameter id
|**type**  |String|**Yes**| Always 'Parameter'
|label  | String |No| A short text label for the parameter
|description |String|No|  A description of the parameter
|data-type |String|No|  The data type of the parameter values [integer, float, string]
|unit |<<col-unit,unit>> object|No|  A description of the units of the parameter values
|**observedProperty** |<<col-observed_property,observedProperty>> object|**Yes**|  A formal definition of the parameter
|extent |<<col-extent,Extent>> object|No|  Information on the spatio-temporal extent of the parameter values (if different from other parameters in the collection)
|measurementType |<<col-measurement_type,measurementType>> object|No| Information on how the value was derived

|==========================

==== Model (UML) TBD

==== Model (OWL, or at least a formal and stable mapping of concepts to URIs) TBD

==== JSON schema
Currently the schema is defined in https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collections/parameterNames.yaml[YAML]

==== JSON-LD context TBD e.g. https://github.com/covjson/specification/blob/master/contexts/context.jsonld

==== Validator
https://cite.opengeospatial.org/te2/about/ogcapi-edr10/1.0/site/[OGC API - Environmental Data Retrieval 1.0 Conformance Test Suite, Beta, Version 0.5, 2022-11-08]. 

==== Examples
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html[Standard].

==== Further guidance
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html[Standard].

==== Media type
application/json

==== Link relation types
Link relation types are not applicable from a Parameter Name Object. (??)
