=== Parameter-Name Object
==== Overview
The `parameter-name` object provides information about a data parameter supported by a Collection. The Collection may expose several `parameter-name` objects, as a set of key-value pairs, where the key is the name of the parameter and the value is a <<col-parameter, Parameter-Name>> object.

There is also a very similar, compatible, JSON object defined in the https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc22[CoverageJSON specification] called `parameter`. 

This building block is called `parameter-name` to try to avoid confusion with the JSON use of `parameter`. 

==== Source Reference
It is defined in the https://docs.ogc.org/is/19-086r5/19-086r5.htm[OGC API-EDR V1.0.1 specification, Section 8.2.1.3] which is maintained by the OGC EDR API Standard Working Group using this https://github.com/opengeospatial/ogcapi-environmental-data-retrieval[OGC GitHub repository].

==== Maturity
Stable

[[col-parameter]]
==== Pre-defined Properties of the Parameter-Name Object 
[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Parameter Object
|==========================
|Field Name|Type|Required|Description
|id  |String|No| parameter id
|**type**  |String|**Yes**| Always 'Parameter'
|label  | String |No| A short text label for the parameter
|description |String|No|  A description of the parameter
|data-type |String|No|  The data type of the parameter values [integer, float, string]
|unit |<<col-unit,unit>> object|No|  A description of the units of the parameter values
|**observedProperty** |<<col-observed_property,observedProperty>> object|**Yes**|  A formal definition of the parameter
|extent |<<col-extent,Extent>> object|No|  Information on the spatio-temporal extent of the parameter values (if different from other parameters in the collection)
|measurementType |<<col-measurement_type,measurementType>> object|No| Information on how the value was derived

|==========================

==== Model (UML) TBD

==== Model (OWL, or at least a formal and stable mapping of concepts to URIs) TBD

==== JSON schema
Currently the schema is https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/schemas/collections/parameterNames.yaml[defined in YAML]

==== JSON-LD context TBD e.g. https://github.com/covjson/specification/blob/master/contexts/context.jsonld

==== Validator
https://cite.opengeospatial.org/te2/about/ogcapi-edr10/1.0/site/[OGC API - Environmental Data Retrieval 1.0 Conformance Test Suite, Beta, Version 0.5, 2022-11-08]. 

==== Examples
See some Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html#parameter-name[Standard, Clause 8.2.1.3].

Also, some examples from an implementation

===== Example 1, Height of the Maximum Wind (for aviation)
----
"max_wind_ht":{
   "type":"Parameter",
   "id":"max_wind_ht",
   "description":"ICAO Standard Atmosphere Reference Height [m]",
   "unit":{
      "symbol":{
         "value":"m",
         "type":"http://codes.wmo.int/common/unit/_m"
      },
      "label":"m"
   },
   "observedProperty":{
      "id":"http://codes.wmo.int/grib2/codeflag/4.2/_0-3-3",
      "label":"ICAO Standard Atmosphere Reference Height [m]"
   }
},
----
===== Example 2, Geopotential Height, measured in geopotential meters
----
"geo_pot_ht":{
               "type":"Parameter",
               "id":"geo_pot_ht",
               "description":"Geopotential height [gpm]",
               "unit":{
                  "symbol":{
                     "value":"gpm",
                     "type":"http://codes.wmo.int/common/unit/_gpm"
                  },
                  "label":"gpm"
               },
               "observedProperty":{
                  "id":"http://codes.wmo.int/grib2/codeflag/4.2/_0-3-5",
                  "label":"Geopotential height [gpm]"
                  }
              },
----
===== Example 3, Relative Humidity, as a percentage
----
            "rh":{
               "type":"Parameter",
               "id":"rh",
               "description":"Relative humidity [%]",
               "unit":{
                  "symbol":{
                     "value":"%",
                     "type":"http://codes.wmo.int/common/unit/percent"
                  },
                  "label":"%"
               },
               "observedProperty":{
                  "id":"http://codes.wmo.int/grib2/codeflag/4.2/_0-1-1",
                  "label":"Relative humidity [%]"
               }
            }
----
==== Further guidance
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html[Standard].

==== Media type
application/json

==== Link relation types
Link relation types do not seem applicable for a Parameter Name Object. Possibly `describedby`old be useful.
