=== Parameter Names Object
==== Overview
The parameter-names object provides information about the data parameters supported by the collection, as a set of key-value pairs, where the key is the name of the parameter and the value is a <<col-parameter, Parameter>> object i.e. as a Dictionary (Python) or HashMap(Java).

==== Source Reference
It is defined in the https://docs.ogc.org/is/19-086r5/19-086r5.htm[OGC API-EDR V1.0.1 specification, Section 8.2.1.3] which is maintained by the OGC EDR API Standard Working Group using this https://github.com/opengeospatial/ogcapi-environmental-data-retrieval[OGC GitHub repository].

==== Maturity
Mature

[[col-parameter]]
==== Parameter Object pre-defined properties
[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Parameter Object
|==========================
|Field Name|Type|Required|Description
|id  |String|No| parameter id
|**type**  |String|**Yes**| Always 'Parameter'
|label  | String |No| A short text label for the parameter
|description |String|No|  A description of the parameter
|data-type |String|No|  The data type of the parameter values [integer, float, string]
|unit |<<col-unit,unit>> object|No|  A description of the units of the parameter values
|**observedProperty** |<<col-observed_property,observedProperty>> object|**Yes**|  A formal definition of the parameter
|extent |<<col-extent,Extent>> object|No|  Information on the spatio-temporal extent of the parameter values (if different from other parameters in the collection)
|measurementType |<<col-measurement_type,measurementType>> object|No| Information on how the value was derived

|==========================

==== Model (UML) TBD
==== Model (OWL, or at least a formal and stable mapping of concepts to URIs) TBD
==== JSON schema TBD
schemas/json-collection.yaml

==== JSON-LD context TBD
==== validator TBD
==== examples TBD
==== link to further guidance TBD
==== Media type TBD
application/json

==== Link relation types
The following link relation types are commonly used in links from a Parameter Name Object:

Table 2. Outgoing link relation types

Link relation type 	Description

items
REQUIRED. Refers to the items in the collection, for example, a Features resource, if the itemType is "feature".
This link relation type will not be registered with IANA. In the future, it may be superseded by the search link relation type.

search
RECOMMENDED. Refers to the items in the collection, for example, a Features resource, if the itemType is "feature", with support for filtering features using spatial, temporal and thematic selection criteria.
This link relation type will in the future supersede the items link relation type, so it is recommended to already include this link.

self
REQUIRED. Link to the resource in the current representation.







