=== Cube Query
==== Overview
The `Cube` query returns a data cube defined by the  `bbox` and `z` parameters.
The results are further filtered by the constraints defined by the following query parameters:

[#cube-def-table,reftext='{table-caption} {counter:table-num}']
.Cube query structure
[cols="2,1,1,2,3"]
|====
|Query Parameter| Type | Required|Description|Examples
a| **bbox**

* <<req_core_rc-bbox-definition,definition>> 

* <<req_core_rc-bbox-response,rules>>|String|**Yes** a| The coordinates are defined by a BBOX string 
Only data that has a geometry that intersects the <<area-definition,area>> defined by the <<req_core_rc-bbox-definition,bbox>>
are selected.

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2

bbox=minx,miny,maxx,maxy

The X and Y coordinates are values in the coordinate system defined by the crs query parameter.
If crs is not defined, the values will be assumed to be WGS84 longitude/latitude coordinates and heights will be assumed to be in metres above mean sea level. a| * `bbox=-6.0,50.0,-4.35,52.0`
a| **z**

* <<req_edr_z-definition,definition>> 

* <<req_edr_z-response,rules>>     |String  |No|  The vertical level to return data for (available options defined in the vertical attribute of the extent section in the <<collection_metadata_desc, collections>> metadata response) a| * `z=850` 
* `z=1000,900,850,700` 
* `z=2/100`
a| **datetime**

* <<req_collections_rc-time-definition,definition>> 

* <<req_core_rc-time-response,rules>> |String  |No| Datetime range to return data (the available range is defined in the the temporal attribute of the extent section in the <<collection_metadata_desc, collections>> metadata response) a| * `datetime=2018-02-12T00:00Z` 
* `datetime=2018-02-12T00:00/2018-03-18T12:31Z`
* `datetime=2018-02-12T00:00Z,2018-02-12T01:00Z,2018-02-14T12:00Z`
a| **parameter-name**

* <<req_edr_parameters-definition,definition>> 

* <<req_edr_parameters-response,rules>> |String  |No| Comma delimited list of parameter names available options listed in the **parameter_names** section of the <<collection_metadata_desc, collections>> metadata response a| * `parameter-name=Visibility,Air%20Temperature``
a| **crs**

* <<req_edr_crs-definition,definition>> 

* <<req_edr_crs-response,rules>>    |String|No|  coordinate reference system identifier for the **coords** values and output data (available options listed in the <<collection_metadata_desc, collections>> metadata response) a| * `crs=EPSG:4326` 
* `crs=A_CUSTOM_LABEL`
a| **f**

* <<req_edr_f-definition,definition>> 

* <<req_edr_f-response,rules>>  |String|No| Data format for the output data (available options listed in the <<collection_metadata_desc, collections>> response), schemas describing JSON and XML outputs can be defined in the OpenAPI documentation (see https://swagger.io/docs/specification/data-models/) a| * `f=GeoJSON`
* `f=netCDF4`
* `f=CoverageJSON`
* `f=CSV`
|====

#If a client request has a *bbox* value which includes height values and defines a *z* query parameter the *z* query parameter will be the definition of the requested height value#

==== Source Reference
It is defined in the https://docs.ogc.org/is/19-086r5/19-086r5.htm[OGC API-EDR V1.0.1 specification, Section 8.2.4] which is maintained by the OGC EDR API Standard Working Group using this https://github.com/opengeospatial/ogcapi-environmental-data-retrieval[OGC GitHub repository].

==== Maturity
Stable

==== Model (UML) TBD

==== Model (OWL, or at least a formal and stable mapping of concepts to URIs) TBD

==== JSON schema
Currently the schema is https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/blob/master/standard/openapi/request-bodies/cube.yaml[defined in YAML]

==== JSON-LD context TBD e.g. https://github.com/covjson/specification/blob/master/contexts/context.jsonld

==== Validator
https://cite.opengeospatial.org/te2/about/ogcapi-edr10/1.0/site/[OGC API - Environmental Data Retrieval 1.0 Conformance Test Suite, Beta, Version 0.5, 2022-11-08]. 

==== Examples
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html#parameter-name[Standard, Clause 8.2.4].

===== Example 1 Request data within a specified `bbox` for a single level and single time
----
.../cube?bbox=-6.0,50.0,-4.35,52.0&z=850&datetime=2018-02-12T00:00Z
----
===== Example 2 Request data within a specified `bbox` for a single level and a range of times
----
.../cube?bbox=-6.0,50.0,-4.35,52.0&z=850&datetime=2018-02-12T00:00/2018-03-18T12:31Z
----
===== Example 3 Request data within a specified `bbox` for a single time and for several levels
----
.../cube?bbox=-6.0,50.0,-4.35,52.0&datetime=2018-02-12T00:00Z&z=1000,900,850,700
----
===== Example 4 Request data within a specified `bbox` for a range of levels and a range of times
----
.../cube?bbox=-6.0,50.0,-4.35,52.0&z=2/100&datetime=2018-02-12T00:00/2018-03-18T12:31Z
----
==== Further guidance
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/19-086r5.html[Standard].

==== Media type
application/json

==== Link relation types
Link relation types do not seem applicable for a Cube Query. Possibly `describedby`could be useful.
