identifier-prefix: ogc.
name: OGC Main
abstract: OGC Specification Elements packaged as FAIR Building Blocks.
description: |
  
  The OGC Building Blocks register provides an overview of a series of [building blocks](https://ogcincubator.github.io/bblocks-docs/) managed by the OGC community through a variety of processes:
  
  - formal standards publication processes the Standards Working Groups
  - agreements with other standards bodies (eg. ISO)
  - community hosted examples of re-use (profiles and extensions of OGC standards)
  - informal "incubator" processes where more than one project needs a solution, and appropriate SWG scope is yet to be determined
  
  ![](https://lucid.app/publicSegments/view/9d075f82-8611-4f32-83eb-994143669cc8/image.png)


  Notes:
  
  1. Policies are in preparation for naming and governance of these sub-registers, and this is subject to change pending adoption of such policies.
  1. Building Block identification will be designed to support transition between governance domains without change using symbolic references.
  1. A formal definition of Building Blocks and the level of "granularity" they represent with respect to the OGC Modular Specification is TBD.

imports: []

sparql:
  push: https://defs-dev.opengis.net/fuseki/data
  graph: https://blocks.ogc.org/
  query: https://defs-dev.opengis.net/fuseki/query
