= Header: Content-Crs

Version: 1.0.0

== Overview

Because of the inconsistent provision of coordinate reference system (CRS) metadata in geospatial encodings and the continued confusion caused by the axis order of coordinates, this header provides a mechanism for a server to clearly and unambiguously assert the CRS being used in a response document independent of the requested output format.

https://github.com/cportele/ogcapi-building-blocks#building-block-maturity[*Maturity*]: Stable

== Examples

.Bounding box parameter example
=================
The `Content-Crs` header in the response below asserts that any coordinates in the response are in the coordinate reference system World Mercator (used for very small scale conformal mapping) as requested using the `crs` query parameter. 

[source,TEXT]
----
$ curl -i "https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395"

HTTP/1.1 200 OK
Date: Sun, 24 May 2020 15:30:56 GMT
Content-Type: application/geo+json
Content-Language: en
Content-Crs: <http://www.opengis.net/def/crs/EPSG/0/3395>
Link: <https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395&f=json>; rel="self"; title="This document"; type="application/geo+json"
Link: <https://example.com/api/v1/collections/poi/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F3395&f=html>; rel="alternate"; title="This document as HTML"; type="text/html"
Link: <https://example.com/api/v1/collections/poi>; rel="collection"; title="The collection the feature belongs to"
Vary: Accept-Language,Accept-Encoding
Content-Length: 1064

...
----
=================

== Description

The value of the `Content-Crs` header is a URI identifying the coordinate reference system used in the response document according to the following grammar for `CRS-header`.

[source,TEXT]
----
CRS-header = "Content-Crs" ":" CRS-value

CRS-value = "<" URI-reference ">"
----

== OpenAPI 3.0 specification

ifdef::env-github[]
include::schemas/header-content-crs.yaml[]
endif::[]
ifndef::env-github[]
[source,YAML]
----
include::schemas/header-content-crs.yaml[]
----
endif::[]

=== Source Reference

http://www.opengis.net/doc/IS/ogcapi-features-2/1.0#_coordinate_reference_system_information_independent_of_the_feature_encoding[OGC API - Features, Part 2, 6.3.4: Coordinate reference system information independent of the feature encoding]