= Parameter: bbox

Version: 1.0.1

== Overview

The `bbox` query parameter provides a simple mechanism for filtering resources based on their location. It selects all resources that intersect a rectangle (map view) or box (including height information).

https://github.com/cportele/ogcapi-building-blocks#building-block-maturity[*Maturity*]: Mature

== Examples

.Bounding box parameter example
=================
The following bounding box parameter includes the 48 contiguous states of the United States of America.

[source,TEXT]
----
bbox=-124.7844079,24.7433195,-66.9513812,49.3457868
----
=================

== Description

`bbox` is a query parameter that may be applied in GET requests on a collection of resources.

The parameter, if provided, selects the resources with a spatial extent that intersects the specified link:json-bbox.adoc[bounding box].

The coordinates of the bounding box are in longitude, latitude and optionally ellipsoidal height unless a different coordinate reference system is specified in the link:parameter-bbox-crs.adoc[query parameter `bbox-crs`].

The `bbox` parameter matches all resources in the collection that are not associated with a spatial geometry, too.

If a resource has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the spatial extent or all relevant geometries.

== OpenAPI 3.0 specification

ifdef::env-github[]
include::schemas/parameter-bbox.yaml[]
endif::[]
ifndef::env-github[]
[source,YAML]
----
include::schemas/parameter-bbox.yaml[]
----
endif::[]

=== Source Reference

http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#_parameter_bbox[OGC API - Features, Part 1, 7.15.3: Parameter bbox]