description: 'Basic-YPR: Basic GeoPose using yaw, pitch, and roll to specify orientation'
definitions:
  angles:
    type: object
    properties:
      yaw:
        type: number
        x-jsonld-id: http://example.com/geopose/yaw
      pitch:
        type: number
        x-jsonld-id: http://example.com/geopose/pitch
      roll:
        type: number
        x-jsonld-id: http://example.com/geopose/roll
    required:
    - yaw
    - pitch
    - roll
  Position:
    type: object
    properties:
      lat:
        type: number
        x-jsonld-id: http://example.com/geopose/lat
      lon:
        type: number
        x-jsonld-id: http://example.com/geopose/lon
      h:
        type: number
        x-jsonld-id: http://example.com/geopose/h
    required:
    - lat
    - lon
    - h
type: object
properties:
  position:
    $ref: '#/definitions/Position'
    x-jsonld-id: http://example.com/geopose/position
  angles:
    $ref: '#/definitions/angles'
    x-jsonld-id: http://example.com/geopose/angles
required:
- position
- angles
x-jsonld-prefixes:
  geopose: http://example.com/geopose/
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
x-jsonld-extra-terms:
  latitude: http://www.w3.org/2003/01/geo/wgs84_pos#lat
  rotations: http://example.com/geopose/rotations
  height: http://example.com/geopose/height
  longitude: http://www.w3.org/2003/01/geo/wgs84_pos#long
$id: https://schemas.opengis.net/geopose/1.0/schemata/GeoPose.Basic.YPR.Schema.json
