description: annotated link with role and conformance
$defs:
  coderef:
    $ref: http://blocks.ogc.org/annotated-schemas/ogc-utils/iri-or-curie/schema.yaml
  coderefs:
    $ref: http://blocks.ogc.org/annotated-schemas/ogc-utils/iri-or-curie/schema.yaml#/$defs/MultipleOrObjectOrNull
allOf:
- $ref: http://blocks.ogc.org/annotated-schemas/ogc-utils/json-link/schema.yaml
- properties:
    role:
      $ref: '#/$defs/coderef'
      x-jsonld-id: http://www.w3.org/ns/dx/prof/hasRole
      x-jsonld-type: '@id'
    conformsTo:
      $ref: '#/$defs/coderefs'
      x-jsonld-id: http://purl.org/dc/terms/conformsTo
      x-jsonld-type: '@id'
  required:
  - role
x-jsonld-prefixes:
  prof: http://www.w3.org/ns/dx/prof/
  dct: http://purl.org/dc/terms/
