$schema: https://json-schema.org/draft/2020-12/schema
description: feature with geometry by reference
properties:
  type:
    $ref: http://opengeospatial.github.io/bblocks/annotated-schemas/ogc-utils/iri-or-curie/schema.yaml
    x-jsonld-id: '@type'
  references:
    type: array
    items:
      $ref: http://opengeospatial.github.io/bblocks/annotated-schemas/ogc-utils/iri-or-curie/schema.yaml
    x-jsonld-id: https://purl.org/geojson/vocab#relatedFeatures
    x-jsonld-type: '@id'
    x-jsonld-container: '@list'
required:
- references
- type
x-jsonld-extra-terms:
  LineString: https://purl.org/geojson/vocab#LineString
x-jsonld-prefixes:
  geojson: https://purl.org/geojson/vocab#
  csdm: https://linked.data.gov.au/def/csdm/
  dct: http://purl.org/dc/terms/
