= Bounding Box

Version: 1.0.1

== Overview

The bounding box JSON object describes a simple spatial extent of a resource. For OGC API's this could be a feature, a feature collection or a dataset, but it can be used in any JSON resource that wants to communicate its rough location. The extent is "simple" in that the bounding box does not describe the precise location and shape of the resource, but provides an axis-aligned approximation of the spatial extent that can be used as an initial test whether two resources are potentially intersecting each other.

The bounding box is also useful when displaying a resource in a map to determine the initial map view.

https://github.com/cportele/ogcapi-building-blocks#building-block-maturity[*Maturity*]: Mature

== Description

A bounding box is provided as an array of four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth):

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Minimum value, coordinate axis 3 (optional)
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2
* Maximum value, coordinate axis 3 (optional)

If the value consists of four numbers, the coordinate reference system is WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified.

If the value consists of six numbers, the coordinate reference system is WGS 84 longitude/latitude/height (http://www.opengis.net/def/crs/OGC/0/CRS84h) unless a different coordinate reference system is specified.

How a different coordinate reference system is specified depends on the context in which the bounding box is used.

For WGS 84 longitude/latitude the values are in most cases the sequence of minimum longitude, minimum latitude, maximum longitude and maximum latitude. However, in cases where the box spans the antimeridian the first value (west-most box edge) is larger than the third value (east-most box edge).

If the vertical axis is included, the third and the sixth number are the bottom and the top of the 3-dimensional bounding box.

=== Example

.Axis-aligned minimum bounding box of the 48 contiguous states of the United States of America (JSON)
=================
[source,JSON]
----
[-124.7844079, 24.7433195, -66.9513812, 49.3457868]
----
=================

=== Schema

ifdef::env-github[]
include::schemas/json-bbox.yaml[]
endif::[]
ifndef::env-github[]
[source,YAML]
----
include::schemas/json-bbox.yaml[]
----
endif::[]

=== Source Reference

http://www.opengis.net/doc/IS/ogcapi-features-1/1.0#_response_4[OGC API - Features, Part 1, 7.13.2: Feature Collections Response]

== Alternate Representation: Text 

The text representation of a bounding box is based on the JSON representation and represents the array as comma-separated values. 

=== Example

.Axis-aligned minimum bounding box of the 48 contiguous states of the United States of America (Text)
=================
[source,TEXT]
----
-124.7844079,24.7433195,-66.9513812,49.3457868
----
=================

