=== Grid
==== Overview
Grid is a coverage domain type:

- A domain with Grid domain type MUST have the axes `"x"` and `"y"` and MAY have the axes `"z"` and `"t"`.

==== Source Reference
It is defined in the https://docs.ogc.org/is/19-086r5/19-086r5.html#grid[OGC CoverageJSON Community Standard, Section 9.10.1] which is maintained by the OGC Coverages Standard Working Group using this https://github.com/opengeospatial/CoverageJSON[OGC GitHub repository].

==== Maturity
Stable

==== Pre-defined Properties of the Grid Domain Object 
[width="100%",cols="22%,22%,14%,42%",frame="topbot",options="header"]
.Polygon Domain Object
|==========================
|Field Name|Type|Required|Description
|domainType |String|**Yes**|Always `"Grid"`
|axes |String|**Yes**| Always `"composite"`
|composite |String|**Yes**|Always `"point"`
|coordinates |Array|**Yes**|Always `["x","y"]`
|values |Array|**Yes**| The coordinate pairs for one point
|z |Number|No| An optional vertical coordinate
|t |String|No| An optional time coordinate in ISO8601 format 
|==========================

==== Model (UML) TBD

==== Model (OWL, or at least a formal and stable mapping of concepts to URIs) TBD

==== JSON schema TBD
Currently the schema is https://schemas.opengeospatial.net/covjson/1.0/domainBase.json

==== JSON-LD context TBD 
E.g. https://schemas.opengeospatial.net/covjson/... TBD

==== Validator TBD

==== Examples
See some Examples in the https://opengeospatial.github.io/ogcna-auto-review/21-069.html#grid[Standard, Clause 9.10.1].

===== Example 1, Grid Domain - rectangle
A point defined by the coordinates `(1.0,20.0)`, at vertical coordinate `1`, and for the time `"2008-01-01T04:00:00Z"`
----
{
  "type": "Domain",
  "domainType": "Grid",
  "axes": {
    "x": { "values": [1,2,3] },
    "y": { "values": [20,21] },
    "z": { "values": [1] },
    "t": { "values": ["2008-01-01T04:00:00Z"] }
  },
  "referencing": [...]
}
----
===== Example 2, Coverage using a Grid Domain 
A coverage of temperature for the domain as in the previous example.
----
{
  "type" : "Coverage",
  "domain" : {
    "type" : "Domain",
    "domainType" : "Grid",
    "axes": {
      "x": { "values": [1,2,3] },
      "y": { "values": [20,21] },
      "z": { "values": [1] },
      "t": { "values": ["2008-01-01T04:00:00Z"] }
    },
    "referencing": [...]
  },
  "parameters" : {
    "temperature": {...}
  },
  "ranges" : {
    "temperature" : {
      "type" : "NdArray",
      "dataType": "float",
      "axisNames": ["t", "z", "y", "x"],
      "shape": [1, 1, 2, 3],
      "values" : [...]
    }
  }
}
----
==== Further guidance
See the Examples in the https://opengeospatial.github.io/ogcna-auto-review/21-069.html[Standard].

==== Media type
application/vnd.cov+json

==== Link relation types
Link relation types do not seem applicable for a Point Object. Possibly `describedby` could be useful.
