type: object
required:
- links
- collections
properties:
  links:
    type: array
    items:
      $ref: ../../../ogc-utils/schemas/json-link.yaml
  collections:
    type: array
    items:
      $ref: ../ogc_collection/schema.yaml
