$schema: https://json-schema.org/draft/2020-12/schema
$id: https://beta.schemas.opengis.net/json-fg/time.json
title: the value of the 'time' member
description: This JSON Schema is part of JSON-FG version 0.3.0.
oneOf:
- type: 'null'
- type: object
  minProperties: 1
  properties:
    date:
      $ref: '#/$defs/date'
      x-jsonld-id: http://www.w3.org/2006/time#hasTime
      x-jsonld-type: http://www.w3.org/2001/XMLSchema#date
    timestamp:
      $ref: '#/$defs/timestamp'
      x-jsonld-id: http://www.w3.org/2006/time#hasTime
      x-jsonld-type: http://www.w3.org/2001/XMLSchema#dateTime
    interval:
      $ref: '#/$defs/interval'
      x-jsonld-id: http://www.w3.org/2006/time#hasTime
      x-jsonld-container: '@list'
$defs:
  date:
    type: string
    pattern: ^\d{4}-\d{2}-\d{2}$
  timestamp:
    type: string
    pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$
  interval:
    type: array
    minItems: 2
    maxItems: 2
    items:
      anyOf:
      - oneOf:
        - $ref: '#/$defs/date'
        - type: string
          enum:
          - ..
      - oneOf:
        - $ref: '#/$defs/timestamp'
        - type: string
          enum:
          - ..
x-jsonld-prefixes:
  time: http://www.w3.org/2006/time#
  xsd: http://www.w3.org/2001/XMLSchema#
